const PREFIX = "@@exercise/";

export const EXERCISE_INIT = `${PREFIX}EXERCISE_INIT`;
export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
export const EXERCISE_INITIATE = `${PREFIX}EXERCISE_INITIATE`;
export const GET_EXERCISES_SUCCESS = `${PREFIX}GET_EXERCISES_SUCCESS`;
export const GET_EXERCISES_FAIL = `${PREFIX}GET_EXERCISES_FAIL`;
export const EXERCISE_FAILURE = `${PREFIX}EXERCISE_FAILURE`;
export const GET_LEG_EXERCISES_SUCCESS = `${PREFIX}GET_LEG_EXERCISES_SUCCESS`;
export const GET_ARM_EXERCISES_SUCCESS = `${PREFIX}GET_ARM_EXERCISES_SUCCESS`;
export const GET_ABS_EXERCISES_SUCCESS = `${PREFIX}GET_ABS_EXERCISES_SUCCESS`;
export const GET_API_EXERCISES_SUCCESS = `${PREFIX}GET_API_EXERCISES_SUCCESS`;
export const GET_API_EXERCISES_FAILURE = `${PREFIX}GET_API_EXERCISES_FAILURE`;
export const SAVE_API_EXERCISES_SUCCESS = `${PREFIX}SAVE_API_EXERCISES_SUCCESS`;
export const GET_ANALYTICS_SUCCESS = `$${PREFIX}GET_ANALYTICS_SUCCESS`;
