const PREFIX = "@@food/";

export const FOOD_INIT = `${PREFIX}FOOD_INIT`;
export const RESET_NOTIFICATION = `${PREFIX}RESET_NOTIFICATION`;
export const FOOD_INITIATE = `${PREFIX}FOOD_INITIATE`;
export const PREDICT_FOOD_SUCCESS = `${PREFIX}PREDICT_FOOD_SUCCESS`;
export const FOOD_FAILURE = `${PREFIX}FOOD_FAILURE`;
export const MEAL_PLAN_SUCCESS = `${PREFIX}MEAL_PLAN_SUCCESS`;
