const PREFIX = "@@heartRate/";

export const INIT_HEART_RATE = `${PREFIX}INIT_HEART_RATE`;

export const ON_CALCULATE_HEART_RATE = `${PREFIX}ON_CALCULATE_HEART_RATE`;
export const FAILED = `${PREFIX}FAILED`;
export const SET_HEART_RATE = `${PREFIX}SET_HEART_RATE`;
export const ON_RECEIVE_ANALYSIS = `${PREFIX}ON_RECEIVE_ANALYSIS`;
export const INITIALIZE_ANALYSIS = `${PREFIX}INITIALIZE_ANALYSIS`;
